name: 'PHP CodeSniffer Check'
description: 'Helps to detect violations of coding standards with phpcs'
author: 'Ilya Chekalsky'
inputs:
  enable_warnings:
    description: 'Enable checking for warnings (-w)'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-circle'
  color: 'green'
