name: 'PHP_CodeSniffer Check with Annotations'
description: 'PHPCS checker with auto annotations out of the box'
author: 'Ilya Chekalsky'
inputs:
  enable_warnings:
    description: 'Enable checking for warnings (-w)'
    required: false
    default: ''
  phpcs_bin_path:
    description: 'Path to phpcs binary'
    required: false
    default: 'phpcs'
  installed_paths:
    description: 'Setting the installed standard paths'
    required: false
    default: ''
  only_changed_files:
    description: 'Run linter on changed files only'
    required: false
    default: ''
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is stored
      in memory and used to ask the Github API for a list of files changed in
      the PR.

      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.

      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    required: false
    default: ${{ github.token }}
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'zap'
  color: 'purple'
