name: 'PHP_CodeSniffer Check with Annotations'
description: 'PHPCS checker with auto annotations out of the box'
author: 'Ilya Chekalsky'
inputs:
  enable_warnings:
    description: 'Enable checking for warnings (-w)'
    required: false
    default: ''
  phpcs_bin_path:
    description: 'Path to phpcs binary'
    required: false
    default: 'phpcs'
  installed_paths:
    description: 'Setting the installed standard paths'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'zap'
  color: 'purple'
